### ISSUE TITLE
Missing Function

### ISSUE THREAD

**Issue by royda** [Wolfenswan/ws_fnc#31]
ws_fnc_showText is referenced in the "broadcast" function, however "ws_fnc_showText" is not found in the init.sqf nor anywhere else. Please advise. Thank you.

**Comment by Wolfenswan** [comment]
It's compiled directly in the ws_fnc_broadcast function and then used in BIS_fnc_MP to display the text.

The whole function is a bit hacky as it was made back in the early early A3 days.
